/**
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 */

var fibGen = require('./../lib/fibs');
var _ = require('lodash');

var fib1 = new fibGen (4000000);
var fib2 = new fibGen (4000);


var getResult = function getResult (fib) {
	var count = 0;
	var curr = 0;
	while(!fib.isMax()) {
		curr = fib.getNext();
		if (curr % 2 === 0) {
			count += curr;
		}
	}
	return count;
}
/* Using Parials ;) */
var resultOne = _.partial(getResult, fib1);
var resultTwo = _.partial(getResult, fib2);

console.log(resultOne());
console.log(resultTwo());
fib1.reset()
console.log(resultOne());
console.log(resultTwo());


